
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '/public/css/siteStandard.css';
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>   

<meta name="robots" content="noindex, nofollow"   
/> {/* Add this meta tag */}
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}style={{ paddingTop: '150px' }}
      >
        {children}
      </body>
    </html>
  );
}
