
//import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import '/public/css/siteStandard.css';
// import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Endicott Clay Products Company",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>   

<meta name="robots" content="noindex, nofollow"   
/> 
</Head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}style={{ paddingTop: '100px' } }
      >
        {children}
      </body>
    </html>
  );
}
export function generateMetadata() { // Use generateMetadata to set the title
  return {
    title: "Endicott Clay Products Company",
  };
}